sudo: false
language: node_js
install:
  - pip install --user virtualenv
  - virtualenv .
  - bin/pip install --upgrade transitfeed pytz
  - npm i
node_js:
#  - 'stable'
  - '7'
  - '6'
script:
  - echo todo; exit 1
  - ls -lh dest
  - bin/feedvalidator.py --memory_db --output=CONSOLE ./dest
