sudo: false
language: node_js
install:
  - npm i
  - pip install --user virtualenv
  - virtualenv .
  - bin/pip install --upgrade transitfeed
node_js:
  - 'stable'
script:
  - npm run build
  - bin/feedvalidator.py -m ./dest
