sudo: false
language: node_js
install:
  - npm i
  - pip install virtualenv
  - virtualenv .
  - bin/pip install --upgrade transitfeed
node_js:
  - 'stable'
before_script:
  - bin/feedvalidator.py -h
script:
  - npm run build
