sudo: false
language: node_js
before_install:
  - sudo pip install --upgrade pip
install:
  - npm i
  - pip install --upgrade transitfeed
node_js:
  - 'stable'
before_script:
  - feedvalidator.py -h
script:
  - npm run build
