sudo: false
language: node_js
install:
  - pip install --user virtualenv
  - virtualenv .
  - bin/pip install --upgrade transitfeed pytz
  - npm i
node_js:
  - 'stable'
  - '8'
  - '7'
  - '6'
script:
  - ./cli.js -d test
  - ls -lh test/*.txt
  - bin/feedvalidator.py --memory_db --output=CONSOLE ./test
